title: 'Vijay K. | Cloud and DevOps with Vijay'
email: vijay@mevijay.dev
description: >- # this means to ignore newlines until "baseurl:"
  This project is a showcase of how to setup a portfolio website using GitHub Pages, 
  with the main accent put on the blogging part.
baseurl: '/gp-blog' # the subpath of your site, e.g. /blog
url: 'https://mevijay.com'
twitter_username: sharmavijay86
github_username: sharmavijay86

permalink: /:collection/:year-:month-:day-:title:output_ext
show_excerpts: true

# Build settings
theme: minima
plugins:
  - jekyll-feed